# Build a Hugo container for website development
FROM klakegg/hugo:ext-debian

# Update and add packages to image
RUN apt update -qq && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
    bash \
    vim
